name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Code auschecken (mit deinem eingefügten Hash)
      - name: Checkout Code
        uses: actions/checkout@4f48394bbbc026f6c4b19d6a74ecf00ea8f0e24a # v4

      # PHP einrichten (Standard-Action für PHP-Projekte)
      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155f35d18d060e152ef32230a104033c4eb # v2
        with:
          php-version: "8.2" # Deine Mindestanforderung laut composer.json
          coverage: none

      # Abhängigkeiten installieren
      - name: Install Dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      # Prüfen, ob die composer.json valide ist
      - name: Validate Composer
        run: composer validate --strict
